from pathlib import Path

import streamlit as st

from insightsql.application import InsightSQLService, to_record
from insightsql.config import Settings
from insightsql.domain.exceptions import InsightSQLError
from insightsql.infrastructure.database import SQLiteRepository
from insightsql.infrastructure.llm import OpenAIQueryGenerator


@st.cache_resource
def build_service() -> InsightSQLService:
    settings = Settings.from_environment(Path(__file__).resolve().parent)
    repository = SQLiteRepository(settings.database_path, settings.max_rows)
    generator = OpenAIQueryGenerator(
        api_key=settings.openai_api_key,
        model=settings.openai_model,
        timeout=settings.llm_timeout_seconds,
    )
    return InsightSQLService(generator, repository, settings.max_rows)


def render_result(record) -> None:
    st.markdown(f"**Answer**  \n{record.explanation}")
    if record.result is None:
        return
    if record.result.truncated:
        st.info("The result was limited to the configured maximum number of rows.")
    if record.result.rows:
        st.dataframe(record.result.rows, use_container_width=True, hide_index=True)
        numeric_columns = [
            column
            for column in record.result.columns
            if record.result.rows and isinstance(record.result.rows[0].get(column), (int, float))
        ]
        if len(numeric_columns) == 1 and len(record.result.rows) > 1:
            labels = [str(row.get(record.result.columns[0], "")) for row in record.result.rows]
            chart_data = {"label": labels}
            chart_data[numeric_columns[0]] = [row.get(numeric_columns[0]) for row in record.result.rows]
            st.bar_chart(chart_data, x="label", y=numeric_columns[0])
    else:
        st.info("The query returned no rows.")


def main() -> None:
    st.set_page_config(page_title="InsightSQL", page_icon="SQL", layout="wide")
    st.title("InsightSQL")
    st.caption("Ask questions about your workforce data in plain English.")

    if "history" not in st.session_state:
        st.session_state.history = []
    with st.sidebar:
        st.header("Query history")
        show_sql = st.checkbox("Show generated SQL", value=True)
        if not st.session_state.history:
            st.caption("Your submitted questions will appear here.")
        for index, record in enumerate(reversed(st.session_state.history)):
            label = record.question[:60] + ("..." if len(record.question) > 60 else "")
            with st.expander(label, expanded=False):
                st.caption(record.created_at.strftime("%Y-%m-%d %H:%M UTC"))
                if record.error:
                    st.error(record.error)
                else:
                    st.write(record.explanation)
                    if show_sql:
                        st.code(record.sql, language="sql")

    question = st.text_area(
        "Your question",
        placeholder="How many active employees are in each department?",
        height=110,
        label_visibility="visible",
    )
    submitted = st.button("Ask InsightSQL", type="primary", use_container_width=False)
    if submitted:
        try:
            answer = build_service().ask(question)
            record = to_record(answer)
            st.session_state.history.append(record)
            st.subheader("Result")
            render_result(record)
            with st.expander("Query details"):
                st.write(f"**Generated by:** {record.source}")
                if show_sql:
                    st.code(record.sql, language="sql")
                else:
                    st.caption("Enable SQL visibility in the sidebar to inspect the generated query.")
        except InsightSQLError as exc:
            st.error(str(exc))
        except Exception:
            st.error("InsightSQL could not complete that request. Please try again or contact support.")


if __name__ == "__main__":
    main()
